### ISSUE TITLE
support: can't make auto work

### ISSUE THREAD

**Issue by AlexandrosMelissas** [waldronmatt/pnpm-turborepo-auto-boilerplate#1]
Hey Mat, it's me again. My repo is private so i've sent you an invite, if you could take a look at the repo setup. I've managed to make auto actually version my repo but it doesnt seem to detect my packages even if i start fresh with no tags or releases. So when i make a change in app A and commit with conventional commit with fix:  or pr with label with patch, it bumps my root version from 1.0.0 to 1.0.1. And so on.

I only want github releases and no publish, hence i only use "conventional commits" and "git-tag" plugins.

**Comment by waldronmatt** [comment]
Try removing `"private": true,` under `apps/panel/package.json` which might be causing it to not publish. Try making a mock commit for `apps/panel` and a separate mock commit for `apps/api` to see if that triggers both to version independently.

**Comment by AlexandrosMelissas** [comment]
Hmm that doesn't seem to work either. I think now i'm absolutely sure that even if i delete the tags and releases the bumping will remain the same because of the commits. So for example, i still get feat changes because i did it once. So maybe i should get rid of the commits in main + releases + tags and try your idea again.

**Comment by AlexandrosMelissas** [comment]
And that still won't work. It's basically a clean repo with 0 commits. I create seperate commits for the apps,i push, v0.0.1 release gets created. Something is happening and it just won't see my package.json files? Or maybe something is missing in my package.json files

**Comment by AlexandrosMelissas** [comment]
I've also noticed you don't use git tags plugin. How does tagging work without that plugin?

**Comment by waldronmatt** [comment]
I would try using without the `git-tags` plugin as a test. That might be interfering with the default tag generation. As for this repo's setup, I'm not certain, but I think auto automatically takes care of the tags via the `shipit` command via https://intuit.github.io/auto/docs/generated/shipit and https://intuit.github.io/auto/docs/generated/shipit

If there's some weirdness still, I would try to make an exact clone of this repo and get that working first. And then progressively add the rest of your setup incrementally. More time consuming, but it would help identify what exactly is causing the issue.

**Comment by AlexandrosMelissas** [comment]
Yeah i am going to try that as well. Thank you so much for your shared thoughts and time.
